### ISSUE TITLE
Issues on Chrome

### ISSUE THREAD

**Issue by pascaleperry** [sherpa-marketing/interactive-white-paper#13]
The client (of course) has issues with the view.  I can't see how she gets this - latest version of Chrome
[issues on chrom.docx](https://github.com/sherpa-marketing/interactive-white-paper/files/2010239/issues.on.chrom.docx)

**Comment by mgsmith57** [comment]
@pascaleperry I can't see what is wrong with the screenshots. What am I looking at here?

**Comment by pascaleperry** [comment]
Hardly any of the content displays on the pages - she has to scroll down for all of it.

Have shown what I see in Chrome as a comparison
[issues on chrom.docx](https://github.com/sherpa-marketing/interactive-white-paper/files/2010317/issues.on.chrom.docx)
